# These are supported funding model platforms

patreon: GoldpawsStuff
ko_fi: GoldpawsStuff
liberapay: GoldpawsStuff
custom: ["https://www.paypal.me/GoldpawsStuff", "https://www.buymeacoffee.com/GoldpawsStuff"]
