# These are supported funding model platforms

patreon: GoldpawsStuff
ko_fi: GoldpawsStuff
liberapay: GoldpawsStuff
#custom: ["https://www.buymeacoffee.com/GoldpawsStuff", "https://www.paypal.me/GoldpawsStuff"]
