name: Feature request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: [enhancement]
assignees: Goldpaw
body:
- type: checkboxes
  attributes:
    label: Is this feature request for AzeriteUI for Dragonflight?
    description: Please note that this is the issue tracker for the Dragonflight version of AzeriteUI. For the Wrath Classic version visit [https://github.com/GoldpawsStuff/AzeriteUI4/issues](../../AzeriteUI4/issues)
    options:
    - label: Yes, I understand. This is for Dragonflight.
      required: true
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if an issue already exists for the feature your request.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
