name: Package Addon Release
run-name: ${{ github.ref_name }} push run 🚀
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - custom-build
    tags:
      - '*'
jobs:
  build-addon:
    name: Build 🧱
    runs-on: ubuntu-24.04
    env:
      GITHUB_OAUTH: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - with:
        fetch-depth: 0

      - name: Package Addon
        uses: BigWigsMods/packager@07a3e3ce80d58f9bd79794243692f2f22630b7bb
        with:
          args: -m .pkgmeta
